name: frontend
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  http: ^0.13.4
  go_router: ^3.1.0
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.2+1
  path_provider: ^2.0.10
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0
  build_runner: ^2.1.11

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
